/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState } from "react";
import { useGLTF } from "@react-three/drei";

export default function Shoe(props) {
	const { nodes, materials } = useGLTF("/models/shoe.gltf");
	console.log("nodes: ", nodes);
	// const [hovered, setHover] = useState(false);

	const lacesClick = (type) => {
		console.log("clickLaces: ", type);
	};

	const soleClick = (flag) => {
		console.log("soleClick: ", flag);
	};

	return (
		<group {...props} dispose={null}>
			<mesh
				onClick={(e) => lacesClick("laces")}
				castShadow
				receiveShadow
				geometry={nodes.shoe.geometry}
				material={materials.laces}
				material-color="green"
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.shoe_1.geometry}
				material={materials.mesh}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.shoe_2.geometry}
				material={materials.caps}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.shoe_3.geometry}
				material={materials.inner}
			/>
			<mesh
				onClick={(e) => soleClick(true)}
				castShadow
				receiveShadow
				geometry={nodes.shoe_4.geometry}
				material={materials.sole}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.shoe_5.geometry}
				material={materials.stripes}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.shoe_6.geometry}
				material={materials.band}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.shoe_7.geometry}
				material={materials.patch}
			/>
		</group>
	);
}

useGLTF.preload("/models/shoe.gltf");
